[2023-11-21 16:19:41,434] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-11-21 16:20:00,507] [basehttp.py:187] [basehttp:log_message] [INFO]- "POST /api/testmain HTTP/1.1" 301 0
[2023-11-21 16:20:00,523] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /api/testmain/ HTTP/1.1" 200 48
[2023-11-21 16:20:11,977] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\02_Program\04_Examination\Examination\StudentExamination\views.py changed, reloading.
[2023-11-21 16:20:13,007] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-11-21 16:20:49,745] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/testmain/
Traceback (most recent call last):
  File "D:\baiduwangpan\python_virtualenv\python_vx\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\baiduwangpan\python_virtualenv\python_vx\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\02_Program\04_Examination\Examination\StudentExamination\views.py", line 201, in main_index
    return JsonResponse(json.dumps(all_data))
  File "D:\baiduwangpan\python\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "D:\baiduwangpan\python\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "D:\baiduwangpan\python\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "D:\baiduwangpan\python\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type QuerySet is not JSON serializable
[2023-11-21 16:20:49,785] [basehttp.py:187] [basehttp:log_message] [ERROR]- "POST /api/testmain/ HTTP/1.1" 500 145
[2023-11-21 16:21:15,409] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\02_Program\04_Examination\Examination\StudentExamination\views.py changed, reloading.
[2023-11-21 16:21:16,542] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-11-21 16:21:19,197] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/testmain/
Traceback (most recent call last):
  File "D:\baiduwangpan\python_virtualenv\python_vx\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\baiduwangpan\python_virtualenv\python_vx\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\02_Program\04_Examination\Examination\StudentExamination\views.py", line 202, in main_index
    return JsonResponse(json.dumps(all_data))
  File "D:\baiduwangpan\python\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "D:\baiduwangpan\python\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "D:\baiduwangpan\python\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "D:\baiduwangpan\python\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type QuerySet is not JSON serializable
[2023-11-21 16:21:19,203] [basehttp.py:187] [basehttp:log_message] [ERROR]- "POST /api/testmain/ HTTP/1.1" 500 145
[2023-11-21 16:22:21,076] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\02_Program\04_Examination\Examination\StudentExamination\views.py changed, reloading.
[2023-11-21 16:22:22,009] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-11-21 16:22:26,642] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/testmain/
Traceback (most recent call last):
  File "D:\baiduwangpan\python_virtualenv\python_vx\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\baiduwangpan\python_virtualenv\python_vx\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\02_Program\04_Examination\Examination\StudentExamination\views.py", line 202, in main_index
    return JsonResponse(json.dumps(all_data))
  File "D:\baiduwangpan\python\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "D:\baiduwangpan\python\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "D:\baiduwangpan\python\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "D:\baiduwangpan\python\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type QuerySet is not JSON serializable
[2023-11-21 16:22:26,645] [basehttp.py:187] [basehttp:log_message] [ERROR]- "POST /api/testmain/ HTTP/1.1" 500 145
[2023-11-21 16:23:44,464] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\02_Program\04_Examination\Examination\StudentExamination\views.py changed, reloading.
[2023-11-21 16:23:45,482] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-11-21 16:23:56,495] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/testmain/
Traceback (most recent call last):
  File "D:\baiduwangpan\python_virtualenv\python_vx\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\baiduwangpan\python_virtualenv\python_vx\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\02_Program\04_Examination\Examination\StudentExamination\views.py", line 202, in main_index
    return JsonResponse(json.loads(all_data))
  File "D:\baiduwangpan\python\lib\json\__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not QuerySet
[2023-11-21 16:23:56,498] [basehttp.py:187] [basehttp:log_message] [ERROR]- "POST /api/testmain/ HTTP/1.1" 500 145
[2023-11-21 16:25:36,551] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\02_Program\04_Examination\Examination\StudentExamination\views.py changed, reloading.
[2023-11-21 16:25:37,485] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-11-21 16:25:41,540] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/testmain/
Traceback (most recent call last):
  File "D:\baiduwangpan\python_virtualenv\python_vx\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\baiduwangpan\python_virtualenv\python_vx\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\02_Program\04_Examination\Examination\StudentExamination\views.py", line 202, in main_index
    return JsonResponse(json.loads(all_data))
  File "D:\baiduwangpan\python\lib\json\__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not QuerySet
[2023-11-21 16:25:41,543] [basehttp.py:187] [basehttp:log_message] [ERROR]- "POST /api/testmain/ HTTP/1.1" 500 145
[2023-11-21 16:36:54,312] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\02_Program\04_Examination\Examination\StudentExamination\views.py changed, reloading.
[2023-11-21 16:36:55,437] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-11-21 16:37:10,617] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/testmain/
Traceback (most recent call last):
  File "D:\baiduwangpan\python_virtualenv\python_vx\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\baiduwangpan\python_virtualenv\python_vx\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\02_Program\04_Examination\Examination\StudentExamination\views.py", line 202, in main_index
    return JsonResponse(json.loads(all_data))
  File "D:\baiduwangpan\python\lib\json\__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not QuerySet
[2023-11-21 16:37:10,620] [basehttp.py:187] [basehttp:log_message] [ERROR]- "POST /api/testmain/ HTTP/1.1" 500 145
[2023-11-21 16:43:20,358] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/testmain/
Traceback (most recent call last):
  File "D:\baiduwangpan\python_virtualenv\python_vx\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\baiduwangpan\python_virtualenv\python_vx\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\02_Program\04_Examination\Examination\StudentExamination\views.py", line 202, in main_index
    return JsonResponse(json.loads(all_data))
  File "D:\baiduwangpan\python\lib\json\__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not QuerySet
[2023-11-21 16:43:20,360] [basehttp.py:187] [basehttp:log_message] [ERROR]- "POST /api/testmain/ HTTP/1.1" 500 145
[2023-11-21 16:50:30,732] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/testmain/
Traceback (most recent call last):
  File "D:\baiduwangpan\python_virtualenv\python_vx\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\baiduwangpan\python_virtualenv\python_vx\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\02_Program\04_Examination\Examination\StudentExamination\views.py", line 202, in main_index
    return JsonResponse(json.loads(all_data))
  File "D:\baiduwangpan\python\lib\json\__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not QuerySet
[2023-11-21 16:50:30,735] [basehttp.py:187] [basehttp:log_message] [ERROR]- "POST /api/testmain/ HTTP/1.1" 500 145
[2023-11-21 16:50:58,001] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\02_Program\04_Examination\Examination\StudentExamination\views.py changed, reloading.
[2023-11-21 16:50:58,945] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-11-21 16:51:01,406] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/testmain/
Traceback (most recent call last):
  File "D:\baiduwangpan\python_virtualenv\python_vx\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\baiduwangpan\python_virtualenv\python_vx\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\02_Program\04_Examination\Examination\StudentExamination\views.py", line 202, in main_index
    return JsonResponse(json.loads(all_data))
  File "D:\baiduwangpan\python\lib\json\__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not QuerySet
[2023-11-21 16:51:01,409] [basehttp.py:187] [basehttp:log_message] [ERROR]- "POST /api/testmain/ HTTP/1.1" 500 145
[2023-11-21 16:52:01,215] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\02_Program\04_Examination\Examination\StudentExamination\views.py changed, reloading.
[2023-11-21 16:52:02,144] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-11-21 16:52:06,420] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/testmain/
Traceback (most recent call last):
  File "D:\baiduwangpan\python_virtualenv\python_vx\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\baiduwangpan\python_virtualenv\python_vx\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\02_Program\04_Examination\Examination\StudentExamination\views.py", line 202, in main_index
    return JsonResponse(json.loads(all_data))
  File "D:\baiduwangpan\python\lib\json\__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not QuerySet
[2023-11-21 16:52:06,423] [basehttp.py:187] [basehttp:log_message] [ERROR]- "POST /api/testmain/ HTTP/1.1" 500 145
[2023-11-21 16:53:31,101] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\02_Program\04_Examination\Examination\StudentExamination\views.py changed, reloading.
[2023-11-21 16:53:32,076] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-11-21 16:53:35,267] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/testmain/
Traceback (most recent call last):
  File "D:\baiduwangpan\python_virtualenv\python_vx\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\baiduwangpan\python_virtualenv\python_vx\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\02_Program\04_Examination\Examination\StudentExamination\views.py", line 202, in main_index
    return JsonResponse(json.loads(all_data))
  File "D:\02_Program\04_Examination\Examination\StudentExamination\views.py", line 132, in __init__
    super().__init__(*args, **kwargs, json_dumps_params={"ensure_ascii": False})
  File "D:\baiduwangpan\python_virtualenv\python_vx\lib\site-packages\django\http\response.py", line 684, in __init__
    raise TypeError(
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
[2023-11-21 16:53:35,279] [basehttp.py:187] [basehttp:log_message] [ERROR]- "POST /api/testmain/ HTTP/1.1" 500 145
[2023-11-21 16:53:41,446] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\02_Program\04_Examination\Examination\StudentExamination\views.py changed, reloading.
[2023-11-21 16:53:42,493] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-11-21 16:53:43,266] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/testmain/
Traceback (most recent call last):
  File "D:\baiduwangpan\python_virtualenv\python_vx\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\baiduwangpan\python_virtualenv\python_vx\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\02_Program\04_Examination\Examination\StudentExamination\views.py", line 203, in main_index
    return JsonResponse(json.loads(all_data))
  File "D:\02_Program\04_Examination\Examination\StudentExamination\views.py", line 132, in __init__
    super().__init__(*args, **kwargs, json_dumps_params={"ensure_ascii": False})
  File "D:\baiduwangpan\python_virtualenv\python_vx\lib\site-packages\django\http\response.py", line 684, in __init__
    raise TypeError(
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
[2023-11-21 16:53:43,268] [basehttp.py:187] [basehttp:log_message] [ERROR]- "POST /api/testmain/ HTTP/1.1" 500 145
[2023-11-21 16:56:01,163] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\02_Program\04_Examination\Examination\StudentExamination\views.py changed, reloading.
[2023-11-21 16:56:02,328] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-11-21 16:56:04,604] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/testmain/
Traceback (most recent call last):
  File "D:\baiduwangpan\python_virtualenv\python_vx\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\baiduwangpan\python_virtualenv\python_vx\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\02_Program\04_Examination\Examination\StudentExamination\views.py", line 203, in main_index
    return JsonResponse(json.loads(all_data))
  File "D:\02_Program\04_Examination\Examination\StudentExamination\views.py", line 132, in __init__
    super().__init__(*args, **kwargs, json_dumps_params={"ensure_ascii": False})
  File "D:\baiduwangpan\python_virtualenv\python_vx\lib\site-packages\django\http\response.py", line 684, in __init__
    raise TypeError(
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
[2023-11-21 16:56:04,607] [basehttp.py:187] [basehttp:log_message] [ERROR]- "POST /api/testmain/ HTTP/1.1" 500 145
[2023-11-21 16:56:56,216] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\02_Program\04_Examination\Examination\StudentExamination\views.py changed, reloading.
[2023-11-21 16:56:57,109] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-11-21 16:57:02,886] [basehttp.py:187] [basehttp:log_message] [INFO]- "POST /api/testmain/ HTTP/1.1" 200 294
[2023-11-21 16:57:58,911] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\02_Program\04_Examination\Examination\StudentExamination\views.py changed, reloading.
[2023-11-21 16:57:59,883] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-11-21 16:58:04,715] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\02_Program\04_Examination\Examination\StudentExamination\views.py changed, reloading.
[2023-11-21 16:58:05,639] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-11-21 16:58:08,678] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/testmain/
Traceback (most recent call last):
  File "D:\baiduwangpan\python_virtualenv\python_vx\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\baiduwangpan\python_virtualenv\python_vx\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\02_Program\04_Examination\Examination\StudentExamination\views.py", line 201, in main_index
    all_data = serialize('json',ProductDetails.objects.values().order_by("pid"))
  File "D:\baiduwangpan\python_virtualenv\python_vx\lib\site-packages\django\core\serializers\__init__.py", line 134, in serialize
    s.serialize(queryset, **options)
  File "D:\baiduwangpan\python_virtualenv\python_vx\lib\site-packages\django\core\serializers\base.py", line 136, in serialize
    concrete_model = obj._meta.concrete_model
AttributeError: 'dict' object has no attribute '_meta'
[2023-11-21 16:58:08,702] [basehttp.py:187] [basehttp:log_message] [ERROR]- "POST /api/testmain/ HTTP/1.1" 500 145
[2023-11-21 16:58:23,411] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\02_Program\04_Examination\Examination\StudentExamination\views.py changed, reloading.
[2023-11-21 16:58:24,397] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-11-21 16:58:32,382] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\02_Program\04_Examination\Examination\StudentExamination\views.py changed, reloading.
[2023-11-21 16:58:33,318] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-11-21 16:58:43,596] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/testmain/
Traceback (most recent call last):
  File "D:\baiduwangpan\python_virtualenv\python_vx\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\baiduwangpan\python_virtualenv\python_vx\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\02_Program\04_Examination\Examination\StudentExamination\views.py", line 200, in main_index
    all_data = list('json',ProductDetails.objects.values().order_by("pid"))
TypeError: list expected at most 1 argument, got 2
[2023-11-21 16:58:43,598] [basehttp.py:187] [basehttp:log_message] [ERROR]- "POST /api/testmain/ HTTP/1.1" 500 145
[2023-11-21 16:58:58,482] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\02_Program\04_Examination\Examination\StudentExamination\views.py changed, reloading.
[2023-11-21 16:58:59,489] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-11-21 16:59:01,417] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/testmain/
Traceback (most recent call last):
  File "D:\baiduwangpan\python_virtualenv\python_vx\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\baiduwangpan\python_virtualenv\python_vx\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\02_Program\04_Examination\Examination\StudentExamination\views.py", line 200, in main_index
    all_data = list('json',ProductDetails.objects.values())
TypeError: list expected at most 1 argument, got 2
[2023-11-21 16:59:01,420] [basehttp.py:187] [basehttp:log_message] [ERROR]- "POST /api/testmain/ HTTP/1.1" 500 145
[2023-11-21 16:59:24,703] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\02_Program\04_Examination\Examination\StudentExamination\views.py changed, reloading.
[2023-11-21 16:59:25,653] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-11-21 16:59:27,504] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/testmain/
Traceback (most recent call last):
  File "D:\baiduwangpan\python_virtualenv\python_vx\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\baiduwangpan\python_virtualenv\python_vx\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\02_Program\04_Examination\Examination\StudentExamination\views.py", line 201, in main_index
    return JsonResponse(json.loads(all_data),safe=False)
  File "D:\baiduwangpan\python\lib\json\__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not list
[2023-11-21 16:59:27,507] [basehttp.py:187] [basehttp:log_message] [ERROR]- "POST /api/testmain/ HTTP/1.1" 500 145
[2023-11-21 16:59:55,144] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\02_Program\04_Examination\Examination\StudentExamination\views.py changed, reloading.
[2023-11-21 16:59:56,125] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-11-21 16:59:59,279] [basehttp.py:187] [basehttp:log_message] [INFO]- "POST /api/testmain/ HTTP/1.1" 200 236
[2023-11-21 17:55:03,904] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\02_Program\04_Examination\Examination\StudentExamination\forms\ThirdParty.py changed, reloading.
[2023-11-21 17:55:05,040] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-11-21 17:55:17,829] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\02_Program\04_Examination\Examination\StudentExamination\forms\ThirdParty.py changed, reloading.
[2023-11-21 17:55:18,771] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-11-21 17:55:38,953] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\02_Program\04_Examination\Examination\StudentExamination\forms\ThirdParty.py changed, reloading.
[2023-11-21 17:55:39,885] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
