[2023-12-18 05:49:41,260] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
[2023-12-18 10:26:43,981] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-18 10:36:44,093] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-18 10:56:44,192] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-18 11:26:44,287] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-19 07:56:31,286] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 289, in get_Logistic
    data = data["data"]["track_info"]["tracking"]["providers"][0]["events"]
KeyError: 'track_info'
[2023-12-19 08:06:31,824] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 289, in get_Logistic
    data = data["data"]["track_info"]["tracking"]["providers"][0]["events"]
KeyError: 'track_info'
[2023-12-19 08:26:31,913] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 289, in get_Logistic
    data = data["data"]["track_info"]["tracking"]["providers"][0]["events"]
KeyError: 'track_info'
[2023-12-19 08:56:32,008] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 289, in get_Logistic
    data = data["data"]["track_info"]["tracking"]["providers"][0]["events"]
KeyError: 'track_info'
[2023-12-19 10:31:23,702] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-19 10:33:24,212] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-19 10:41:24,132] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-19 10:43:24,309] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-19 11:01:24,238] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-19 11:03:24,424] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-19 11:31:24,336] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-19 11:33:24,525] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-20 10:43:27,899] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-20 10:45:28,069] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-20 10:53:28,657] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-20 10:55:29,298] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-20 11:13:28,816] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-20 11:15:29,468] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-20 11:43:29,517] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-20 11:45:29,575] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-21 10:53:33,729] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-21 10:55:33,753] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-21 11:03:33,845] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-21 11:05:33,855] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-21 11:23:33,976] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-21 11:25:33,949] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-21 11:53:34,067] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-21 11:55:34,123] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-22 11:05:42,537] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-22 11:15:42,639] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-22 11:35:42,728] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-22 12:05:42,819] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-23 11:11:26,812] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-23 11:13:26,785] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-23 11:21:26,906] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-23 11:23:26,882] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-23 11:41:26,992] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-23 11:43:26,977] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-23 12:11:27,084] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-23 12:13:27,075] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-24 11:21:49,628] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-24 11:31:49,780] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-24 11:51:49,870] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-24 12:21:49,965] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-24 13:33:04,327] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 289, in get_Logistic
    data = data["data"]["track_info"]["tracking"]["providers"][0]["events"]
KeyError: 'track_info'
[2023-12-24 13:43:04,437] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 289, in get_Logistic
    data = data["data"]["track_info"]["tracking"]["providers"][0]["events"]
KeyError: 'track_info'
[2023-12-24 14:03:04,531] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 289, in get_Logistic
    data = data["data"]["track_info"]["tracking"]["providers"][0]["events"]
KeyError: 'track_info'
[2023-12-24 14:33:04,620] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 289, in get_Logistic
    data = data["data"]["track_info"]["tracking"]["providers"][0]["events"]
KeyError: 'track_info'
[2023-12-25 11:24:31,535] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-25 11:34:31,651] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-25 11:54:31,748] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-25 12:24:31,863] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-26 11:28:07,548] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-26 11:30:04,114] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-26 11:38:07,650] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-26 11:40:04,217] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-26 11:58:07,743] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-26 12:00:04,321] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-26 12:28:07,837] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-26 12:30:04,413] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-27 11:40:34,785] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-27 11:42:35,137] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-27 11:50:34,884] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-27 11:52:35,226] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-27 12:10:34,970] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-27 12:12:35,316] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-27 12:40:35,057] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
[2023-12-27 12:42:35,407] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/getxx/
Traceback (most recent call last):
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/an/python_examin/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./StudentExamination/views.py", line 292, in get_Logistic
    data_dict[data[i]["time_raw"]["date"] + "_" + data[i]["time_raw"]["time"]] = data[i]["description"] + " " + \
TypeError: can only concatenate str (not "NoneType") to str
